language: node_js
node_js:
  - '0.9'
  - '0.10'
  - '0.11'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-front' ]; then cd .. && eval "mv $currentfolder generator-front" && cd generator-front; fi

